# Generated by Django 2.1 on 2018-10-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='all_clsss_name',
            new_name='clsss_name',
        ),
    ]
