# Generated by Django 2.0.7 on 2018-10-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20181017_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='clsss_name',
            new_name='class_name',
        ),
    ]
